import re
from typing import Dict, Any, List

# 1. Map of Devanagari Phonetic English Phrases to clean English
DEVANAGARI_PHONETIC_ENGLISH: Dict[str, str] = {
    # Conversational Sentences & Questions
    r"\b(व्हाट\s*आर\s*यू\s*(?:डूइंग|डुइंग)|व्हॉट\s*आर\s*यू\s*(?:डूइंग|डुइंग))\b": "What are you doing",
    r"\b(हाउ\s*आर\s*यू|हाऊ\s*आर\s*यू)\b": "How are you",
    r"\b(थैंक\s*यू\s*सो\s*मच|थैंक\s*यू\s*वेरी\s*मच)\b": "Thank you so much",
    r"\b(थैंक\s*यू|थैंक्यू|थैंक्स)\b": "Thank you",
    r"\b(यू\s*आर\s*वेलकम)\b": "You are welcome",
    r"\b(वेलकम)\b": "Welcome",
    r"\b(आई\s*एम\s*फाइन|आय\s*एम\s*फाइन|आई\s*ऍम\s*फाइन)\b": "I am fine",
    r"\b(आई\s*एम\s*गुड|आय\s*एम\s*गुड)\b": "I am good",
    r"\b(आई\s*एम\s*ओके|आय\s*एम\s*ओके)\b": "I am OK",
    r"\b(एवरीथिंग\s*(?:इज|इज़|इस)\s*फाइन)\b": "Everything is fine",
    r"\b(नो\s*प्रॉब्लम|नो\s*प्रोब्लम|नो\s*प्रॉब्लम्स)\b": "No problem",
    r"\b(नो\s*इशू|नो\s*इश्यूज|नो\s*इशूज)\b": "No issue",
    r"\b(आई\s*डोंट\s*नो|आय\s*डोंट\s*नो)\b": "I don't know",
    r"\b(आई\s*डोंट\s*थिंक\s*सो|आय\s*डोंट\s*थिंक\s*सो)\b": "I don't think so",
    r"\b(आई\s*थिंक\s*सो|आय\s*थिंक\s*सो)\b": "I think so",
    r"\b(आई\s*थिंक|आय\s*थिंक)\b": "I think",
    r"\b(आई\s*नो|आय\s*नो)\b": "I know",
    r"\b(आई\s*अंडरस्टैंड|आय\s*अंडरस्टैंड)\b": "I understand",
    r"\b(आई\s*सी|आय\s*सी)\b": "I see",
    r"\b(आई\s*फील|आय\s*फील)\b": "I feel",
    r"\b(आई\s*वांट|आय\s*वॉन्ट)\b": "I want",
    r"\b(आई\s*नीड|आय\s*नीड)\b": "I need",
    r"\b(आई\s*टेक|आय\s*टेक)\b": "I take",
    r"\b(आई\s*अग्री|आय\s*अग्री|ही\s*अग्री|आय\s*अग़्री|आई\s*एग्री|आय\s*एग्री)\b": "I agree",
    r"\b(आई\s*डिसअग्री|आय\s*डिसअग्री|डॉन\'?टी?\s*अग्री|डोंट\s*अग्री|डिसअग्री)\b": "I disagree",
    r"\b(आई\s*हैव|आय\s*हॅव|आई\s*हॅव)\b": "I have",
    r"\b(आई\s*डोंट\s*हैव|आय\s*डोंट\s*हॅव)\b": "I don't have",
    r"\b(आई\s*एम|आय\s*एम|आई\s*म)\b": "I am",
    r"\b(स्टॉप\s*द\s*कन्वर्सेशन|स्टॉप\s*कन्वर्सेशन)\b": "Stop the conversation",
    r"\b(स्टॉप\s*द\s*रिकॉर्डिंग|स्टॉप\s*रिकॉर्डिंग)\b": "Stop the recording",
    r"\b(स्टार्ट\s*द\s*कन्वर्सेशन|स्टार्ट\s*कन्वर्सेशन)\b": "Start the conversation",
    r"\b(पॉज\s*द\s*माइक|पॉज़\s*द\s*माइक)\b": "Pause the mic",
    r"\b(रिज्यूम\s*द\s*माइक|रिज़्यूम\s*द\s*माइक)\b": "Resume the mic",
    
    # Greetings & Modifiers
    r"\b(गुड\s*मॉर्निंग)\b": "Good Morning",
    r"\b(गुड\s*आफ्टरनून)\b": "Good Afternoon",
    r"\b(गुड\s*इवनिंग)\b": "Good Evening",
    r"\b(गुड\s*नाइट)\b": "Good Night",
    r"\b(वेरी\s*गुड)\b": "Very Good",
    r"\b(नाइस)\b": "Nice",
    r"\b(श्योर|स्योर)\b": "Sure",
    r"\b(डेफिनेटली)\b": "Definitely",
    r"\b(ऑफ\s*कोर्स|ऑफकोर्स)\b": "Of course",
    r"\b(ऑलराइट)\b": "Alright",
    r"\b(सॉरी)\b": "Sorry",
    r"\b(एक्सक्यूज\s*मी)\b": "Excuse me",
    r"\b(प्लीज|प्लीज़)\b": "Please",
    r"\b(हैलो|हेलो|हाय)\b": "Hello",
    r"\b(बाय\s*बाय|बाय|गुडबाय)\b": "Goodbye",
    
    # Question words & helpers
    r"\b(व्हाट|व्हॉट)\b": "What",
    r"\b(व्हाय|व्हाई)\b": "Why",
    r"\b(व्हेन)\b": "When",
    r"\b(वेयर)\b": "Where",
    r"\b(हू)\b": "Who",
    r"\b(हाउ|हाऊ)\b": "How",
    r"\b(मेबी|मे\s*बी)\b": "Maybe",
    r"\b(नथिंग)\b": "Nothing",
    r"\b(समथिंग)\b": "Something",
    r"\b(एनीथिंग)\b": "Anything",
    r"\b(एवरीथिंग)\b": "Everything",
    
    # Actions & App controls
    r"\b(स्टॉप)\b": "Stop",
    r"\b(स्टार्ट)\b": "Start",
    r"\b(पॉज|पॉज़)\b": "Pause",
    r"\b(रिज्यूम|रिज़्यूम)\b": "Resume",
    r"\b(कैंसिल)\b": "Cancel",
    r"\b(क्लियर)\b": "Clear",
    r"\b(रिपीट)\b": "Repeat",
    r"\b(कन्फर्म)\b": "Confirm",
    r"\b(कन्वर्सेशन)\b": "Conversation",
    r"\b(स्क्रीनशॉट)\b": "Screenshot",
    r"\b(इंप्लीमेंटेशन)\b": "Implementation",
    r"\b(बॉट|रोबोट)\b": "Bot",
    r"\b(सिस्टम)\b": "System",
    r"\b(एप्लीकेशन|ऐप)\b": "App",
    r"\b(ऑनलाइन)\b": "Online",
    r"\b(ऑफलाइन)\b": "Offline",
    r"\b(इंटरनेट)\b": "Internet",
    r"\b(मोबाइल|फोन)\b": "Phone",
    r"\b(मैसेज)\b": "Message",
    r"\b(कॉल)\b": "Call",
    r"\b(वॉइस|वाइस)\b": "Voice",
    r"\b(ऑडियो)\b": "Audio",
    r"\b(वीडियो)\b": "Video",
    r"\b(स्क्रीन)\b": "Screen",
    r"\b(बटन)\b": "Button",
    r"\b(माइक)\b": "Mic",
    r"\b(माइक्रोफोन)\b": "Microphone",
    r"\b(स्पीकर)\b": "Speaker",
    
    # Demographics & Patient Phrases
    r"\b(माय\s*नेम\s*(?:इज|इज़|इस|स)?)\b": "My Name is",
    r"\b(माय\s*एज\s*(?:इज|इज़|इस|स)?)\b": "My Age is",
    r"\b(माय\s*नेम)\b": "My Name",
    r"\b(माय\s*एज)\b": "My Age",
    r"\b(माय\s*जेंडर)\b": "My Gender",
    r"\b(माय\s*डॉक्टर)\b": "My Doctor",
    r"\b(माय\s*रिपोर्ट)\b": "My Report",
    r"\b(माय\s*टेस्ट)\b": "My Test",
    r"\b(माय\s*बीपी)\b": "My BP",
    r"\b(माय\s*शुगर)\b": "My Sugar",
    r"\b(माय\s*वेट)\b": "My Weight",
    r"\b(माय\s*डाइट)\b": "My Diet",
    r"\b(माय\s*फैमिली)\b": "My Family",
    r"\b(माय\s*मेडिसिन|माय\s*मेडिसिन्स)\b": "My Medicines",
    r"\b(माय|माइ)\b": "My",
    r"\b(आई\s*एम\s*मेल|आय\s*एम\s*मेल)\b": "I am Male",
    r"\b(आई\s*एम\s*फीमेल|आय\s*एम\s*फीमेल)\b": "I am Female",
    r"\b(ईयर्स\s*ओल्ड|इयर्स\s*ओल्ड|इयर\s*ओल्ड)\b": "Years Old",
    r"\b(ईयर्स|इयर्स|इयर)\b": "Years",
    r"\b(मंथ्स\s*ओल्ड|मंथ्स|मंथ)\b": "Months",
    r"\b(डेज|डेज़|डे)\b": "Days",
    r"\b(वीक्स|वीक)\b": "Weeks",
    r"\b(मॉर्निंग)\b": "Morning",
    r"\b(इवनिंग)\b": "Evening",
    r"\b(आफ्टरनून)\b": "Afternoon",
    r"\b(नाइट)\b": "Night",
    r"\b(डेली)\b": "Daily",
    r"\b(एवरीडे)\b": "Everyday",
    r"\b(टुडे)\b": "Today",
    r"\b(यस्टरडे)\b": "Yesterday",
    r"\b(टुमॉरो)\b": "Tomorrow",
    r"\b(बिफोर\s*मील्स?|बिफोर\s*फूड)\b": "Before Meal",
    r"\b(आफ्टर\s*मील्स?|आफ्टर\s*फूड)\b": "After Meal",
    r"\b(ब्रेकफास्ट)\b": "Breakfast",
    r"\b(लंच)\b": "Lunch",
    r"\b(डिनर)\b": "Dinner",
    r"\b(एंड|ऐंड)\b": "and",
    r"\b(फॉर)\b": "for",
    r"\b(सिंस)\b": "since",
    
    # Clinical & Medical Phrases
    r"\b(नो\s*डायबिटीज|नो\s*डायबिटिज)\b": "No Diabetes",
    r"\b(नॉट\s*डायबिटिक|नॉन\s*डायबिटिक)\b": "Not Diabetic",
    r"\b(डायबिटिक)\b": "Diabetic",
    r"\b(फास्टिंग\s*ब्लड\s*शुगर|फास्टिंग\s*शुगर)\b": "Fasting Blood Sugar",
    r"\b(पोस्ट\s*प्रांडियल|पोस्ट\s*प्रैंडियल|पीपी\s*शुगर)\b": "Postprandial Sugar",
    r"\b(रैंडम\s*ब्लड\s*शुगर|रैंडम\s*शुगर)\b": "Random Blood Sugar",
    r"\b(ब्लड\s*शुगर|ब्लडशुगर)\b": "Blood Sugar",
    r"\b(ब्लड\s*प्रेशर)\b": "Blood Pressure",
    r"\b(हार्ट\s*रेट|पल्स\s*रेट|पल्स)\b": "Heart Rate",
    r"\b(चेस्ट\s*पेन)\b": "Chest Pain",
    r"\b(हार्ट\s*अटैक)\b": "Heart Attack",
    r"\b(ब्रीदिंग\s*प्रॉब्लम|ब्रीदिंग\s*इशू|शॉर्टनेस\s*ऑफ\s*ब्रेथ)\b": "Breathing Problem",
    r"\b(इमरजेंसी\s*डिपार्टमेंट)\b": "Emergency Department",
    r"\b(एंबुलेंस|एम्बुलेंस)\b": "Ambulance",
    r"\b(ऑडियो\s*रिकॉर्डिंग)\b": "Audio Recording",
    r"\b(फैमिली\s*हिस्ट्री)\b": "Family History",
    r"\b(यूरिन\s*टेस्ट|ब्लड\s*टेस्ट|लैब\s*टेस्ट)\b": "Lab Test",
    r"\b(टेस्ट\s*रिपोर्ट|लैब\s*रिपोर्ट)\b": "Test Report",
    r"\b(शुगर\s*लेवल)\b": "Sugar Level",
    r"\b(लो\s*शुगर)\b": "Low Sugar",
    r"\b(हाई\s*शुगर)\b": "High Sugar",
    r"\b(ब्लरी\s*विजन|ब्लर्ड\s*विजन)\b": "Blurry Vision",
    r"\b(वेट\s*लॉस)\b": "Weight Loss",
    r"\b(वेट\s*गेन)\b": "Weight Gain",
    r"\b(फ्रीक्वेंट\s*यूरिनेशन|फ्रीक्वेंट\s*यूरिन)\b": "Frequent Urination"
}

# 2. Map of terms that MUST be formatted in English (Latin Script)
# (Longer/Compound terms placed first to avoid partial token overwrites)
ENGLISH_CLINICAL_TERMS: Dict[str, str] = {
    # Demographics (Female placed before Male)
    r"\b(फीमेल|फिमेल|महिला|स्त्री|female)\b": "Female",
    r"(?<!फी)(?<!फि)\b(मेल|पुरुष|पुरूष|male)\b": "Male",
    r"\b(नेम|नाम|name)\b": "Name",
    r"\b(एज|age)\b": "Age",
    r"\b(जेंडर|gender)\b": "Gender",
    r"\b(years?|yrs?|yr)\b": "Years",
    r"\b(months?|mo)\b": "Months",
    r"\bold\b": "Old",
    
    # Clinical & Medical Core
    r"\b(डॉक्टर|डाक्टर|doctor|dr)\b": "Doctor",
    r"\b(डायबिटीज|डायबिटिज|डायबीटीज|diabetes)\b": "Diabetes",
    r"\b(शुगर|sugar)\b": "Sugar",
    r"\b(blood\s*sugar)\b": "Blood Sugar",
    r"\b(fasting\s*blood\s*sugar)\b": "Fasting Blood Sugar",
    r"\b(फास्टिंग|fasting)\b": "Fasting",
    r"\b(एचबी\s*ए\s*वन\s*सी|एचबीए1सी|hba1c|hb\s*a1c)\b": "HbA1c",
    r"\b(टाइप\s*1|टाइप1|type\s*1|type1)\b": "Type 1",
    r"\b(टाइप\s*2|टाइप2|type\s*2|type2)\b": "Type 2",
    r"\b(टाइप\s*1\s*डायबिटीज|type\s*1\s*diabetes)\b": "Type 1 Diabetes",
    r"\b(टाइप\s*2\s*डायबिटीज|type\s*2\s*diabetes)\b": "Type 2 Diabetes",
    r"\b(गेस्टेशनल\s*डायबिटीज|gestational\s*diabetes)\b": "Gestational Diabetes",
    r"\b(blood\s*pressure)\b": "Blood Pressure",
    r"\b(बीपी|bp)\b": "BP",
    
    # Medications & Tests
    r"\b(मेडिसिन|मेडिसिन्स|दवाइयां|दवाइयाँ|medicines?|meds?)\b": "Medicines",
    r"\b(टैबलेट|टैबलेट्स|गोली|tablets?|tab)\b": "Tablet",
    r"\b(इंसुलिन|इन्सुलिन|insulin)\b": "Insulin",
    r"\b(इंजेक्सन|इंजेक्शन|injections?)\b": "Injection",
    r"\b(डोज|डोज़|dose|doses)\b": "Dose",
    r"\b(मेटफॉर्मिन|metformin)\b": "Metformin",
    r"\b(ग्लिमेपिराइड|glimepiride)\b": "Glimepiride",
    r"\b(ग्लिक्लैजाइड|gliclazide)\b": "Gliclazide",
    r"\b(टेनेलिग्लिप्टिन|teneligliptin)\b": "Teneligliptin",
    r"\b(सिटाग्लिप्टिन|sitagliptin)\b": "Sitagliptin",
    r"\b(डैपाग्लिफ्लोज़िन|डापाग्लिफ्लोज़िन|dapagliflozin)\b": "Dapagliflozin",
    r"\b(एम्पैग्लिफ्लोज़िन|empagliflozin)\b": "Empagliflozin",
    r"\b(टेस्ट|tests?)\b": "Test",
    r"\b(रिपोर्ट|reports?)\b": "Report",
    r"\b(प्रिस्क्रिप्शन|prescription)\b": "Prescription",
    r"\b(क्लिनिक|clinic)\b": "Clinic",
    r"\b(अपॉइंटमेंट|appointment)\b": "Appointment",
    r"\b(चेकअप|चेक\s*अप|checkup)\b": "Checkup",
    
    # Symptoms & Organs
    r"\b(यूरिन|urine)\b": "Urine",
    r"\b(यूरिनेशन|urination)\b": "Urination",
    r"\b(फ्रीक्वेंट\s*यूरिन|frequent\s*urine|frequent\s*urination)\b": "Frequent Urination",
    r"\b(फटिग|फटीग|fatigue)\b": "Fatigue",
    r"\b(वीकनेस|weakness)\b": "Weakness",
    r"\b(टायर्डनेस|tiredness)\b": "Tiredness",
    r"\b(डिज्जिनेस|डिजीनेस|dizziness)\b": "Dizziness",
    r"\b(ब्लरी\s*विजन|blurry\s*vision|blurred\s*vision)\b": "Blurry Vision",
    r"\b(विजन|विज़न|vision)\b": "Vision",
    r"\b(वेट\s*लॉस|weight\s*loss)\b": "Weight Loss",
    r"\b(वेट\s*गेन|weight\s*gain)\b": "Weight Gain",
    r"\b(वेट|weight)\b": "Weight",
    r"\b(हाइट|height)\b": "Height",
    r"\b(बीएमआई|bmi)\b": "BMI",
    r"\b(वूंड|wound|wounds)\b": "Wound",
    r"\b(नंबनेस|numbness)\b": "Numbness",
    r"\b(टिंङ्गलिंग|tingling)\b": "Tingling",
    r"\b(स्वेटिंग|sweating)\b": "Sweating",
    r"\b(हेडेक|headache)\b": "Headache",
    r"\b(लो\s*शुगर|low\s*sugar)\b": "Low Sugar",
    r"\b(हाई\s*शुगर|high\s*sugar)\b": "High Sugar",
    
    # Lifestyle & History
    r"\b(एक्सरसाइज|exercise)\b": "Exercise",
    r"\b(वर्कआउट|workout)\b": "Workout",
    r"\b(जिम|gym)\b": "Gym",
    r"\b(योग|योगा|yoga)\b": "Yoga",
    r"\b(वॉक|walk|walking)\b": "Walk",
    r"\b(डाइट|diet)\b": "Diet",
    r"\b(रूटीन|routine)\b": "Routine",
    r"\b(family\s*history)\b": "Family History",
    r"\b(फैमिली|family)\b": "Family",
    r"\b(हिस्ट्री|history)\b": "History",
    r"\b(पेरेंट्स|parents)\b": "Parents",
    r"\b(फादर|father)\b": "Father",
    r"\b(मदर|mother)\b": "Mother",
    r"\b(ब्रदर|brother)\b": "Brother",
    r"\b(सिस्टर|sister)\b": "Sister",
    r"\b(प्रेगनेंसी|प्रेग्नेंसी|pregnancy)\b": "Pregnancy",
    
    # Emergency & Hospital
    r"\b(emergency\s*department)\b": "Emergency Department",
    r"\b(इमरजेंसी|emergency)\b": "Emergency",
    r"\b(chest\s*pain)\b": "Chest Pain",
    r"\b(ब्रीदिंग|breathing)\b": "Breathing",
    r"\b(हॉस्पिटल|hospital)\b": "Hospital",
    r"\b(audio\s*recording)\b": "Audio Recording",
    r"\b(रिकॉर्डिंग|recording)\b": "Recording",
    r"\b(कंसेंट|consent)\b": "Consent",
    r"\b(डिटेल्स|details)\b": "Details",
    r"\b(प्रॉब्लम|problems?)\b": "Problem",
    r"\b(सिम्प्टम्स|symptoms?)\b": "Symptoms",
    r"\b(कंसल्ट|consult)\b": "Consult",
    r"\b(हेल्प|help)\b": "Help",
    r"\b(हेल्थ|health)\b": "Health",
    r"\b(केयर|care)\b": "Care",
    r"\b(लेवल|level)\b": "Level",
    r"\b(नॉर्मल|normal)\b": "Normal",
    r"\b(कंट्रोल|control)\b": "Control",
    r"\b(पॉजिटिव|positive)\b": "Positive",
    r"\b(नेगेटिव|negative)\b": "Negative",
    r"\b(रेगुलर|regular)\b": "Regular",
    r"\b(ओके|ok|okay)\b": "OK",
    r"\b(यस|या|yes|yeah)\b": "Yes",
    r"\b(नो|नाट|नॉट|no|not)\b": "No",
    r"\bmg/dL\b": "mg/dL",
    r"\bmg\b": "mg",
    r"\bml\b": "ml"
}

# 3. Map of Romanized Hinglish words to clean Hindi Devanagari
# Words that are part of conversational Hindi speech when typed/spoken in Latin script
# (Ensures pure English sentences like 'My name is John' or 'I have no problem' are NOT corrupted)
HINGLISH_TO_DEVANAGARI: Dict[str, str] = {
    # Pronouns & Helpers (Specific Romanized Hindi)
    r"\bmera\b": "मेरा",
    r"\bmeri\b": "मेरी",
    r"\bmere\b": "मेरे",
    r"\bmujhe\b": "मुझे",
    r"\bmujhko\b": "मुझको",
    r"\bhum\b": "हम",
    r"\bhamara\b": "हमारा",
    r"\bhamari\b": "हमारी",
    r"\bhamare\b": "हमारे",
    r"\baap\b": "आप",
    r"\baapka\b": "आपका",
    r"\baapki\b": "आपकी",
    r"\baapke\b": "आपके",
    r"\bmain(?!\s+(?:problem|issue|reason|symptom|doctor|hospital))\b": "मैं",
    r"\bmai\b": "मैं",
    r"\btum\b": "तुम",
    r"\btumhara\b": "तुम्हारा",
    r"\byeh\b": "यह",
    r"\bwoh\b": "वह",
    r"\biska\b": "इसका",
    r"\biski\b": "इसकी",
    r"\biske\b": "इसके",
    r"\buska\b": "उसका",
    r"\buski\b": "उसकी",
    r"\buske\b": "उसके",
    
    # Common Verbs & Particles (Hindi specific)
    r"\bhai\b": "है",
    r"\bhain\b": "हैं",
    r"\bhoon\b": "हूँ",
    r"\bhun\b": "हूँ",
    r"\bho\b": "हो",
    r"\btha\b": "था",
    r"\bthi\b": "थी",
    r"\bhota\b": "होता",
    r"\bhoti\b": "होती",
    r"\bhote\b": "होते",
    r"\bho\s*raha\b": "हो रहा",
    r"\bho\s*rahi\b": "हो रही",
    r"\bho\s*rahe\b": "हो रहे",
    r"\braha\b": "रहा",
    r"\brahi\b": "रही",
    r"\brahe\b": "रहे",
    r"\baata\b": "आता",
    r"\baati\b": "आती",
    r"\baate\b": "आते",
    r"\baaya\b": "आया",
    r"\baayi\b": "आई",
    r"\baaye\b": "आए",
    r"\blagta\b": "लगता",
    r"\blagti\b": "लगती",
    r"\blagte\b": "लगते",
    r"\bleta\b": "लेता",
    r"\bleti\b": "लेती",
    r"\blete\b": "लेते",
    r"\ble\s*raha\b": "ले रहा",
    r"\ble\s*rahi\b": "ले रही",
    r"\ble\s*rahe\b": "ले रहे",
    r"\bkarta\b": "करता",
    r"\bkarti\b": "करती",
    r"\bkarte\b": "करते",
    r"\bkar\s*raha\b": "कर रहा",
    r"\bkar\s*rahi\b": "कर रही",
    r"\bkar\s*rahe\b": "कर रहे",
    r"\bkiya\b": "किया",
    r"\bkarwaya\b": "करवाया",
    r"\bkarwayi\b": "करवाई",
    r"\bkaraya\b": "कराया",
    r"\bkarayi\b": "कराई",
    r"\bbatana\b": "बताना",
    r"\bbataye\b": "बताइए",
    r"\bbatao\b": "बताओ",
    r"\bsamajh\b": "समझ",
    r"\bgaya\b": "गया",
    r"\bgayi\b": "गई",
    r"\bgaye\b": "गए",
    r"\bde\s*raha\b": "दे रहा",
    r"\bde\s*rahi\b": "दे रही",
    r"\bdiya\b": "दिया",
    r"\bkhata\b": "खाता",
    r"\bkhati\b": "खाती",
    r"\bkhate\b": "खाते",
    r"\bpeeta\b": "पीता",
    r"\bpeeti\b": "पीती",
    
    # Prepositions, Adverbs, Negations, Affirmations
    r"\baur\b": "और",
    r"\bka\b": "का",
    r"\bki\b": "की",
    r"\bke\b": "के",
    r"\bko\b": "को",
    r"\bse\b": "से",
    r"\bmein\b": "में",
    r"\bpar\b": "पर",
    r"\btak\b": "तक",
    r"\bliye\b": "लिए",
    r"\bkeliye\b": "के लिए",
    r"\bsaath\b": "साथ",
    r"\bpichle\b": "पिछले",
    r"\bpichla\b": "पिछला",
    r"\bpichli\b": "पिछली",
    r"\baajkal\b": "आजकल",
    r"\bpehle\b": "पहले",
    r"\bbaad\b": "बाद",
    r"\btheek\b": "ठीक",
    r"\bthik\b": "ठीक",
    r"\bbahut\b": "बहुत",
    r"\bjada\b": "ज्यादा",
    r"\bjyada\b": "ज्यादा",
    r"\bkuch\b": "कुछ",
    r"\bsab\b": "सब",
    r"\bkabhi\b": "कभी",
    r"\bhamesha\b": "हमेशा",
    r"\broz\b": "रोज",
    r"\brozana\b": "रोजाना",
    r"\bnahi\b": "नहीं",
    r"\bnahin\b": "नहीं",
    r"\bna\b": "ना",
    r"\bmat\b": "मत",
    r"\bhaan\b": "हाँ",
    r"\bha\b": "हाँ",
    r"\bhan\b": "हाँ",
    r"\bhaanji\b": "हाँजी",
    r"\bji\b": "जी",
    r"\bsahab\b": "साहब",
    r"\bsaheb\b": "साहब",
    r"\bkya\b": "क्या",
    r"\bkyun\b": "क्यों",
    r"\bkaise\b": "कैसे",
    r"\bkitna\b": "कितना",
    r"\bkitni\b": "कितनी",
    r"\bkitne\b": "कितने",
    r"\bkaha\b": "कहाँ",
    r"\bkahin\b": "कहीं",
    r"\bkoi\b": "कोई",
    r"\bbilkul\b": "बिल्कुल",
    r"\bzaroor\b": "ज़रूर",
    
    # Body parts, Symptoms, Quantities in Hindi
    r"\bsaal\b": "साल",
    r"\bvarsh\b": "वर्ष",
    r"\bumar\b": "उम्र",
    r"\bayu\b": "आयु",
    r"\bmahine\b": "महीने",
    r"\bhafte\b": "हफ्ते",
    r"\bdin\b": "दिन",
    r"\bpyas\b": "प्यास",
    r"\bpeshab\b": "पेशाब",
    r"\bthakan\b": "थकान",
    r"\bthakawat\b": "थकावट",
    r"\bkamjori\b": "कमजोरी",
    r"\bkamzori\b": "कमज़ोरी",
    r"\bdhundhla\b": "धुंधला",
    r"\bchot\b": "चोट",
    r"\bghav\b": "घाव",
    r"\bdard\b": "दर्द",
    r"\bjalan\b": "जलन",
    r"\bsujan\b": "सूजन",
    r"\bkhujli\b": "खुजली",
    r"\bseene\b": "सीने",
    r"\bchhati\b": "छाती",
    r"\bdil\b": "दिल",
    r"\bhaath\b": "हाथ",
    r"\bpair\b": "पैर",
    r"\bpairo\b": "पैरों",
    r"\bpairon\b": "पैरों",
    r"\baankh\b": "आँख",
    r"\baankhon\b": "आँखों",
    r"\bpani\b": "पानी",
    r"\bpasina\b": "पसीना",
    r"\bchakkar\b": "चक्कर",
    r"\bulti\b": "उल्टी",
    r"\bpet\b": "पेट",
    r"\bgale\b": "गले",
    r"\bsaans\b": "सांस",
    r"\btakleef\b": "तकलीफ",
    r"\btabiyat\b": "तबीयत",
    r"\bkhan\s*pan\b": "खान-पान",
    r"\bkhana\b": "खाना",
    r"\bpeena\b": "पीना",
    r"\bchawal\b": "चावल",
    r"\broti\b": "रोटी",
    r"\bmeetha\b": "मीठा",
    r"\bmithai\b": "मिठाई",
    r"\bnamak\b": "नमक",
    r"\btel\b": "तेल",
    r"\bpariwar\b": "परिवार",
    r"\bmata\b": "माता",
    r"\bpita\b": "पिता",
    r"\bpapa\b": "पापा",
    r"\bmummy\b": "मम्मी",
    r"\bbhai\b": "भाई",
    r"\bbehen\b": "बहन",
    r"\bpatni\b": "पत्नी",
    r"\bpati\b": "पति",
    r"\bbeta\b": "बेटा",
    r"\bbeti\b": "बेटी",
    r"\bbacche\b": "बच्चे",
    r"\bkripya\b": "कृपया",
    r"\bdhanyavad\b": "धन्यवाद",
    r"\bshukriya\b": "शुक्रिया",
    r"\bsubah\b": "सुबह",
    r"\bdopahar\b": "दोपहर",
    r"\bshaam\b": "शाम",
    r"\braat\b": "रात",
    r"\baaj\b": "आज",
    r"\bkal\b": "कल",
    r"\bparso\b": "परसों",
    r"\bhalka\b": "हल्का",
    r"\btez\b": "तेज़",
    r"\bkam\b": "कम",
    r"\bsahi\b": "सही",
    r"\bgalat\b": "गलत",
    r"\bshuru\b": "शुरू",
    r"\bkhatam\b": "खत्म",
    r"\bbas\b": "बस",
    
    # Numbers in Romanized Hindi (Context protected)
    r"\bek\b": "एक",
    r"\b(?:ek|teen|chaar|char|paanch|panch)\s+do\b": "दो",
    r"\bdo\s+(?:saal|mahine|hafte|din|baar|bar|goli|tablet|ghante)\b": "दो",
    r"\bteen\b": "तीन",
    r"\bchaar\b": "चार",
    r"\bchar\b": "चार",
    r"\bpaanch\b": "पाँच",
    r"\bpanch\b": "पाँच",
    r"\bchhe\b": "छह",
    r"\bche\b": "छह",
    r"\bsaat\b": "सात",
    r"\baath\b": "आठ",
    r"\bnau\b": "नौ",
    r"\bdas\b": "दस",
    r"\bgyarah\b": "ग्यारह",
    r"\bbarah\b": "बारह",
    r"\bpandrah\b": "पंद्रह",
    r"\bbees\b": "बीस",
    r"\bpachees\b": "पच्चीस",
    r"\btees\b": "तीस",
    r"\bpaintis\b": "पैंतीस",
    r"\bchalis\b": "चालीस",
    r"\bpachas\b": "पचास",
    r"\bsaath\b": "साठ",
    r"\bsattar\b": "सत्तर",
    r"\bassi\b": "अस्सी",
    r"\bnabbe\b": "नब्बे",
    r"\bsau\b": "सौ"
}


def format_patient_speech_hinglish(text: str) -> str:
    """
    Transforms patient voice or text transcripts into standard Code-Mixed Hindi + English:
    - English words (Name, Age, Gender, Doctor, Diabetes, Type 1/2, Medicines, etc.) are typed in English.
    - Devanagari phonetic English is accurately converted to clean English words.
    - Conversational Hindi speech and Romanized Hinglish are typed in clean Hindi (Devanagari).
    """
    if not text or not text.strip():
        return ""

    formatted = text.strip()

    # Step 1: Convert Devanagari Phonetic English (e.g. "माय नेम इज" -> "My Name is", "आई अग्री" -> "I agree")
    for pattern, eng_repl in DEVANAGARI_PHONETIC_ENGLISH.items():
        formatted = re.sub(pattern, eng_repl, formatted, flags=re.IGNORECASE)

    # Step 2: Ensure all key English clinical/lifestyle terms are formatted in English (Latin Script)
    for pattern, eng_repl in ENGLISH_CLINICAL_TERMS.items():
        formatted = re.sub(pattern, eng_repl, formatted, flags=re.IGNORECASE)

    # Step 3: Replace Romanized Hinglish conversational words with Hindi Devanagari
    for pattern, dewa_repl in HINGLISH_TO_DEVANAGARI.items():
        formatted = re.sub(pattern, dewa_repl, formatted, flags=re.IGNORECASE)

    # Step 4: Normalize numerals and spacing
    formatted = re.sub(r"\s+", " ", formatted).strip()

    return formatted
